version: '3'

services:
  etcd-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: k8s-node
    ports:
      - "2379-2380"
    deploy:
      replicas: ${ETCD_COUNT}

  controlplane:
    image: k8s-node
    ports:
      - "6443"
    deploy:
      replicas: ${CONTROLPLANE_COUNT}

  workernode:
    image: k8s-node
    ports:
      - "80"
      - "22"
      - "443"
    deploy:
      replicas: ${WORKERNODE_COUNT}