#Use the official ubuntu image for k8n nodes 
FROM docker.io/library/ubuntu:latest 

#Environment variable to enable non-interactive mode
ENV DEBIAN_FRONTEND=noninteractive

#Copy the basic dependencies and utilities installation script into the image
COPY  Docker-Container/Setup-utilities.sh /tmp/Setup-utilities.sh

#Make script executable 
RUN chmod +x /tmp/Setup-utilities.sh

#Run script
RUN /tmp/Setup-utilities.sh

# Clean up
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#Specify the default command
CMD ["sleep", "infinity"]

